
//Todo List Also Create In ChatGpt --/prafulpatnecha
List letterMusicList = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
];
List musicBestList = [
  "Sonic Safari",
  "Echo Enclave",
  "Melody Migration",
  "The Infinite Soundscape",
  "Vibe Vault",
  "Echo Odyssey",
  "Rhythmic Reverie",
  "Melody Matrix",
  "Sonic Symphony",
  "Fusion Frequencies",
  "Echo Explorer",
  "Sonic Safari",
  "Melody Maze",
  "Echo Expedition",
  "Harmony Hall",
  "Sonic Solstice",
  "The Infinite Soundscape",
  "Vibe Voyage",
  "Echo Explorer",
  "Rhythm Route",
  "The Infinite Audio",
  "Echo Odyssey",
  "Harmony Horizon",
  "Sonic Shelter",
  "The Beat Bazaar",
  "Fusion Flow",
  "Echo Odyssey",
  "Sonic Safari",
  "The Infinite Frequency",
  "Echo Explorer",
  "Melody Matrix",
  "Sonic Shelter",
  "Echo Odyssey",
  "The Infinite Soundscape",
  "Rhythm Realm",
  "Fusion Frequencies",
  "Echo Enigma",
  "Sonic Spectrum",
  "Harmony Hall",
  "The Infinite Playlist",
  "Rhythm Roadtrip",
  "Echo Odyssey",
  "Fusion Frequencies",
  "Sonic Solstice",
  "Echo Escapade",
  "Harmony Hideaway",
  "Sonic Safari",
  "The Infinite Audio",
  "Echo Expedition",
  "Rhythm Realm",
  "Sonic Shelter",
  "Echo Explorer",
  "Fusion Frequencies",
  "The Infinite Soundscape",
  "Harmony Highway",
  "Echo Escapade",
  "Sonic Safari",
  "Echo Explorer",
  "The Infinite Soundscape",
  "Rhythm Road",
  "Melody Migration",
  "Sonic Safari",
  "Echo Odyssey",
  "The Infinite Playlist",
  "Harmony Hall",
  "Echo Enclave",
  "Sonic Shelter",
  "Melody Mingle",
  "The Infinite Journey",
  "Fusion Frequencies",
  "Echo Expedition",
];
List musicNewNames = [
  "Sonic Voyage",
  "The Ultimate Mix",
  "Harmonic Shuffle",
  "Vibe Vault",
  "Rhythmic Realm",
  "Soundscape Symphony",
  "All Genre Galaxy",
  "Melody Mosaic",
  "The Sound Spectrum",
  "Tune Fusion",
  "Echoes Everywhere",
  "Beat Boulevard",
  "Vibes Unlimited",
  "Musical Medley",
  "Infinite Playlist",
  "Harmony Highway",
  "Sonic Rush",
  "Audio Adventure",
  "Fusion Frequencies",
  "The Mix Master",
  "Melodic Journey",
  "The Beat Blender",
  "Tune Tapestry",
  "Genre Jam",
  "Sound Odyssey",
  "Rhapsody Rave",
  "Electric Eclectics",
  "Symphony of Sounds",
  "Global Grooves",
  "The Beat Box",
  "Dynamic Ditties",
  "Mix & Mash",
  "Sonic Rainbow",
  "Infinite Jams",
  "Playlist Paradise",
  "The Sound Odyssey",
  "Melody Magic",
  "The Vibe Vault",
  "Electric Vibes",
  "Pulse of the Beat",
  "Crossfade Chronicles",
  "Spectrum of Sound",
  "Rhythm & Resonance",
  "The Audio Alchemist",
  "Soundwave Safari",
  "Tune Travel",
  "Playlist Pilgrimage",
  "Sonic Expedition",
  "Vibe Voyage",
  "Tonal Terrain",
  "The Audio Atlas",
  "Beat Blender",
  "Jukebox Journey",
  "Echo Explorers",
  "Harmonic Horizon",
  "Soundscape Soiree",
  "Audio Atmosphere",
  "Infinite Frequencies",
  "Sonic Solstice",
  "The Rhythm Route",
  "Tune Time Machine",
  "The Infinite Jukebox",
  "Euphonic Echoes",
  "Beat Spectrum",
  "Melody Mixer",
  "Harmony Haven",
  "The Genre Genesis",
  "Audio Adventureland",
  "The Beat Buffet",
  "Sonic Safari",
  "Groove Globe",
  "Riff Reverie",
  "Music Mingle",
  "The Vibe Voyage",
  "Tune Trek",
  "The Audio Expedition",
  "Genre Journey",
  "Soundwave Shuffle",
  "Melodic Madness",
  "The Sound Sampler",
  "Groove Guide",
  "Sonic Stream",
  "Echo Explorer",
  "The Beat Bazaar",
  "Melody Maze",
  "Tune Tundra",
  "Fusion Fiesta",
  "Soundwave Safari",
  "The Infinite Echo",
  "Rhythm Roam",
  "Harmony Horizon",
  "Pulse of the World",
  "Melody Melange",
  "Sonic Synergy",
  "Global Groove",
  "Harmony Harbor",
  "Resonant Realms",
  "The Beat Buffet",
  "The Tune Tapestry",
  "Echo Escapade",
  "The Mix Manifest",
  "Infinite Echoes",
  "Audio Arena",
  "Sonic Sphere",
  "The Rhythm Realm",
  "Echo Expedition",
  "Melody Medley",
  "Sound Sanctuary",
  "The Audio Abode",
  "Harmony Hall",
  "Sonic Shelter",
  "Groove Garden",
  "Rhythm Route",
  "The Beat Box",
  "Tune Trails",
  "Fusion Frenzy",
  "Infinite Tunes",
  "Sonic Safari",
  "Vibe Voyage",
  "Melody Magic",
  "The Beat Breeze",
  "Tune Terrain",
  "Echo Expedition",
  "Melody Matrix",
  "Vibe Vault",
  "Infinite Rhapsody",
  "Sound Sphere",
  "Rhythm Roadtrip",
  "The Beatway",
  "Vibe Avenue",
  "Tune Trackers",
  "The Infinite Frequency",
  "Echo Escapade",
  "Harmonic Haven",
  "Sound City",
  "Melodic Map",
  "Sonic Shelter",
  "The Genre Junction",
  "Tune Trailblazers",
  "Echo Enclave",
  "Rhythmic Reverie",
  "Infinite Harmony",
  "Soundscape Safari",
  "Melody Migration",
  "Rhythm Road",
  "Sonic Solstice",
  "Echo Euphoria",
  "Infinite Melodies",
  "Tune Trek",
  "Melody Mirage",
  "Echo Expedition",
  "Rhythmic Rhapsody",
  "Sonic Symphony",
  "The Beat Boulevard",
  "Infinite Soundscapes",
  "Vibe Voyage",
  "Fusion Frequencies",
  "Echo Enigma",
  "Sonic Summit",
  "Tune Trek",
  "Echo Expedition",
  "Sound Symphony",
  "Melody Mingle",
  "Harmonic Highway",
  "The Infinite Playlist",
  "Echo Odyssey",
  "Fusion Flow",
  "Soundscape Soiree",
  "Rhythm Realm",
  "Echo Expedition",
  "Melody Mountain",
  "The Beat Bazaar",
  "Fusion Frontier",
  "The Infinite Audio",
  "Sonic Serenity",
  "Sound Safari",
  "Echo Exploration",
  "Melody Mission",
  "Infinite Vibes",
  "The Rhythm Route",
  "Vibe Voyage",
  "Sonic Stream",
  "Harmony Hideaway",
  "The Infinite Playlist",
  "Rhythm Roadtrip",
  "Melody Matrix",
  "Sound Spectrum",
  "Fusion Frequencies",
  "Sonic Safari",
  "Echo Expedition",
  "The Audio Alchemist",
  "Harmony Horizon",
  "The Infinite Mix",
  "Rhythm Route",
  "Sonic Spectrum",
  "The Echo Escapade",
  "The Sound Safari",
  "Echo Expedition",
  "Sonic Solstice",
  "Fusion Frequencies",
  "Harmony Hall",
  "Echo Explorer",
  "The Audio Atlas",
  "Rhythm Roadtrip",
  "Vibe Voyage",
  "Echo Expedition",
  "Melodic Map",
  "Sonic Spectrum",
  "Echo Enclave",
  "Melody Matrix",
  "Infinite Beats",
  "Echo Explorer",
  "Sonic Safari",
  "The Infinite Mix",
  "Harmony Hideaway",
  "Rhythm Road",
  "Vibe Vault",
  "Sonic Stream",
  "Melody Map",
  "Fusion Frequencies",
  "Echo Escapade",
  "The Infinite Audio",
  "Rhythm Roadtrip",
  "Echo Expedition",
  "Sonic Safari",
  "Fusion Flow",
  "Echo Explorer",
  "Sonic Stream",
  "Rhythm Realm",
  "Infinite Soundscape",
  "Echo Odyssey",
  "Vibe Vault",
  "Sonic Solstice",
  "Echo Expedition",
  "The Infinite Echo",
  "Harmony Highway",
  "Sonic Sphere",
  "The Infinite Journey",
  "Fusion Frequencies",
  "Echo Enclave",
  "Sonic Sanctuary",
  "The Infinite Playlist",
  "Rhythm Roadtrip",
  "Echo Explorer",
  "Melody Migration",
  "The Infinite Echo",
  "Sonic Safari",
  "Echo Expedition",
  "Melody Mingle",
  "The Infinite Soundscape",
  "Harmony Horizon",
  "Echo Enigma",
  "Sonic Safari",
  "Rhythmic Reverie",
  "Infinite Vibes",
  "Echo Explorer",
  "Vibe Voyage",
  "Sonic Solstice",
  "Echo Odyssey",
  "The Infinite Playlist",
  "Harmony Hideaway",
  "Fusion Frequencies",
  "Echo Expedition",
  "Rhythm Realm",
];
int resultValue = 0;
List<String> playlistCategories = [
  "Made For You",  // Personalized playlists
  // "Playlists You May Like",  // Suggested playlists
  "Top Charts",  // Trending music
  "New Releases",  // Latest tracks
  "Trending Now",  // Currently popular songs
  "Weekly Discoveries",  // Weekly new recommendations
  "Fresh Hits",  // Newly popular songs
  "Daily Mix",  // Daily tailored playlists
  "Artist Spotlight",  // Playlists centered around specific artists
  "Mood Booster",  // Uplifting music playlists
  "Chill Vibes",  // Relaxing and laid-back playlists
  "Party Starters",  // Energetic party music
  "Top 50 Global",  // Worldwide top tracks
  "Top 50 Country",  // Top tracks from your country
  "Throwback Hits",  // Old-school and classic hits
  "Summer Vibes",  // Music for the summer season
  "Workout Jams",  // High-energy songs for workouts
  "Road Trip Tunes",  // Songs for long drives
  "Acoustic Favorites",  // Acoustic and unplugged tracks
  "Best of 2024",  // Year-end best music lists
  "Genre Picks",  // Playlists based on different genres (Pop, Rock, Jazz, etc.)
  "Calm & Focus",  // Music for concentration and relaxation
  "Sleep Sounds",  // Soothing sounds for sleep
  "Indie Gems",  // Lesser-known indie music
  "Lo-Fi Beats",  // Chill, lo-fi music
  "Rap Radar",  // Top rap and hip-hop tracks
  "Pop Perfection",  // Latest and greatest pop hits
  "Rock Legends",  // Iconic rock anthems
  "Feel Good Songs",  // Positive, feel-good music
  "Sad Songs",  // Melancholic and emotional tracks
  "Love Songs",  // Romantic ballads and love songs
  "Electronic Anthems",  // Popular electronic music
  "Classical Essentials",  // Classical masterpieces
  "Jazz Vibes",  // Smooth and relaxing jazz tunes
  "Latin Beats",  // Latin music hits
  "Reggae Rhythms",  // Popular reggae music
  "World Music",  // Global music selection
  "Festival Anthems",  // Music from popular music festivals
  "Morning Wake-Up",  // Songs to start your day
  "Night Time Chill",  // Songs to wind down at night
];

